MODEL:
  META_ARCHITECTURE: "ClassLevelBaseline"
  FREEZE_LAYERS: ['']

  BACKBONE:
    NAME: "build_ResAcNet_backbone"
    PRETRAIN: False
    FEAT_DIM: 64
    DEPLOY: False

  HEADS:
    NAME: "ClsHead"
    POOL_LAYER: "avgpool"
    CLS_LAYER: "linear"
    NUM_CLASSES: 4

  LOSSES:
    NAME: ("FocalLoss",)

    CE:
      EPSILON: 0.1
      SCALE: 1.

  PIXEL_MEAN: [127.5, 127.5, 127.5]
  PIXEL_STD: [1, 1, 1]

INPUT:
  SIZE_TRAIN: [112, 112]
  SIZE_TEST: [112, 112]

  DO_FLIP: True
  DO_VERTICAL_FLIP: False
  FLIP_PROB: 0.5

  DO_PAD: True
  PADDING: 10

  CJ:
    ENABLED: True
    BRIGHTNESS: 0.5
    CONTRAST: 0.5

  DO_AUTOAUG: False
  AUTOAUG_PROB: 0.5

  DO_AUGMIX: False
  AUGMIX_PROB: 0.5

  ROT:
    ENABLED: False
    DEGREES: 90
    EXPAND: True

  CUTMIX: False
  MIXUP: False
  FMIX: False
  MIX_ALPHA: 0.2

  REA:
    ENABLED: False
    PROB: 0.5
    VALUE: [127.5, 127.5, 127.5]

  RPT:
    ENABLED: False
    PROB: 0.5

DATASETS:
  ROOT: "/home/ruiming/workspace/pro/facialExpression/data/select/clean_1029"
  NAMES: (("DirReader", "faceonly"),)
  TESTS: (("DirReader", "faceonly"),)
  COMBINEALL: False
  CLASSES: ['angry', 'happy', 'neutral', 'sad']

DATALOADER:
  PK_SAMPLER: True
  NUM_INSTANCE: 128
  NUM_WORKERS: 16

SOLVER:
  FP16_ENABLED: False
  OPT: "Adam"
  MAX_EPOCH: 60
  BASE_LR: 0.001
  BIAS_LR_FACTOR: 2.
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 256

  SCHED: "MultiStepLR"
  STEPS: [20, 40]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 400

  CHECKPOINT_PERIOD: 5

TEST:
  EVAL_PERIOD: 5
  IMS_PER_BATCH: 256

CUDNN_BENCHMARK: True

GC:
  IMAGE_DIR: '/xcli/wheels_cls/wheel_imgs/wheel_imgs_1/test'
  DICT_DIR: '/xcli/weights/ClsWheel_ACNet.pth'
  OUTPUT_DIR: '/xcli/outputs/gradcam'
  IMAGE_SIZE: (300, 300)
  TARGET_LAYER: 'backbone.layer8.block3.relu'

